name: Build and test R package

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         # Include macos-13 to get an intel mac
         os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
    steps:
      - uses: actions/checkout@v4
      - name: Install binary dependencies on ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install -y libhdf5-dev
      - name: Install binary dependencies on mac
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'macos-13' }}
        run: brew install hdf5
      - uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: '3'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            any::testthat
            any::decor
          working-directory: 'ci.package'
      - run: Rscript -e 'testthat::test_local("ci.package")'
